### PR TITLE
fixes to match openvr SDK 0.9.20

### PR DESCRIPTION
**Pull request by grrrwaaa**
these are the changes I needed to make to get this to build on the latest openvr sdk

(note that two of them are actually missing from their own example code, but well documented in their issues...)

### CODE REVIEW

**Comment by num3ric** [comment]
Does this also update the submodule? If not, could you?

**Comment by grrrwaaa** [comment]
ah it didn't, no -- now it does.

of course, pressing deadlines meant this fork now includes a couple of other commits (marked above), one to allow the use of a world-space navigation pose, one to turn of the automatic rendering of controllers and instead provide accessors for the left & right hand controller poses. these seem pretty essential for using the cinder block in production code.

**Comment by grrrwaaa** [comment]
FWIW I've just updated my fork to the 0.9.21 release, and improved the hand controller state tracking -- in case you want to pull that too.

**Comment by num3ric** [comment]
@grrrwaaa I've given you push access since I currently don't have easy access to a vive.

**Pull request merged**
